clc;clear
%% 导出六个环境维度的PC1载荷

load('/path/to/project/Envrion/results_PCA/results_env_6factors.mat', ...
    'PCA_results');

loading_output_dir = ...
    '/path/to/project/Envrion/PCA_loading_tables';

if ~exist(loading_output_dir, 'dir')
    mkdir(loading_output_dir);
end

group_names = { ...
    'SES', ...
    'Parenting', ...
    'SchoolResource', ...
    'SchoolEcology', ...
    'Lifestyle', ...
    'Learning'};

for g = 1:numel(group_names)

    this_name = group_names{g};

    % 优先读取已经保存的loading_table
    if isfield(PCA_results.(this_name), 'loading_table')

        loading_table = ...
            PCA_results.(this_name).loading_table;

    else
        % 如果没有loading_table，则根据item_names和coeff重新构造
        item_names = string( ...
            PCA_results.(this_name).item_names(:));

        pc1_loading = ...
            PCA_results.(this_name).coeff(:,1);

        loading_table = table( ...
            item_names, ...
            pc1_loading, ...
            'VariableNames', { ...
                'variable_name', ...
                'PC1_loading'});
    end

    output_file = fullfile( ...
        loading_output_dir, ...
        [this_name '_PC1_loadings.csv']);

    writetable( ...
        loading_table, ...
        output_file, ...
        'Encoding', 'UTF-8');

    fprintf('%s载荷已导出：%s\n', ...
        this_name, output_file);
end